/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as CatalogCategoryRouteImport } from './routes/catalog.$category'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CatalogSolutionSlugRouteImport } from './routes/catalog.solution.$slug'
import { Route as CatalogBundleSlugRouteImport } from './routes/catalog.bundle.$slug'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const CatalogCategoryRoute = CatalogCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => CatalogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CatalogSolutionSlugRoute = CatalogSolutionSlugRouteImport.update({
  id: '/solution/$slug',
  path: '/solution/$slug',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogBundleSlugRoute = CatalogBundleSlugRouteImport.update({
  id: '/bundle/$slug',
  path: '/bundle/$slug',
  getParentRoute: () => CatalogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cases': typeof CasesRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/privacy': typeof PrivacyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalog/$category': typeof CatalogCategoryRoute
  '/blog/': typeof BlogIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/catalog/bundle/$slug': typeof CatalogBundleSlugRoute
  '/catalog/solution/$slug': typeof CatalogSolutionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cases': typeof CasesRoute
  '/contacts': typeof ContactsRoute
  '/privacy': typeof PrivacyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalog/$category': typeof CatalogCategoryRoute
  '/blog': typeof BlogIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/catalog/bundle/$slug': typeof CatalogBundleSlugRoute
  '/catalog/solution/$slug': typeof CatalogSolutionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cases': typeof CasesRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/privacy': typeof PrivacyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalog/$category': typeof CatalogCategoryRoute
  '/blog/': typeof BlogIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/catalog/bundle/$slug': typeof CatalogBundleSlugRoute
  '/catalog/solution/$slug': typeof CatalogSolutionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/cases'
    | '/catalog'
    | '/contacts'
    | '/privacy'
    | '/blog/$slug'
    | '/catalog/$category'
    | '/blog/'
    | '/catalog/'
    | '/catalog/bundle/$slug'
    | '/catalog/solution/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cases'
    | '/contacts'
    | '/privacy'
    | '/blog/$slug'
    | '/catalog/$category'
    | '/blog'
    | '/catalog'
    | '/catalog/bundle/$slug'
    | '/catalog/solution/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/cases'
    | '/catalog'
    | '/contacts'
    | '/privacy'
    | '/blog/$slug'
    | '/catalog/$category'
    | '/blog/'
    | '/catalog/'
    | '/catalog/bundle/$slug'
    | '/catalog/solution/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CasesRoute: typeof CasesRoute
  CatalogRoute: typeof CatalogRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/catalog/$category': {
      id: '/catalog/$category'
      path: '/$category'
      fullPath: '/catalog/$category'
      preLoaderRoute: typeof CatalogCategoryRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/catalog/solution/$slug': {
      id: '/catalog/solution/$slug'
      path: '/solution/$slug'
      fullPath: '/catalog/solution/$slug'
      preLoaderRoute: typeof CatalogSolutionSlugRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/bundle/$slug': {
      id: '/catalog/bundle/$slug'
      path: '/bundle/$slug'
      fullPath: '/catalog/bundle/$slug'
      preLoaderRoute: typeof CatalogBundleSlugRouteImport
      parentRoute: typeof CatalogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CatalogRouteChildren {
  CatalogCategoryRoute: typeof CatalogCategoryRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  CatalogBundleSlugRoute: typeof CatalogBundleSlugRoute
  CatalogSolutionSlugRoute: typeof CatalogSolutionSlugRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogCategoryRoute: CatalogCategoryRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  CatalogBundleSlugRoute: CatalogBundleSlugRoute,
  CatalogSolutionSlugRoute: CatalogSolutionSlugRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CasesRoute: CasesRoute,
  CatalogRoute: CatalogRouteWithChildren,
  ContactsRoute: ContactsRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
